services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/nginx:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: .
      args:
        HOST_USER_ID: 1000
        HOST_GROUP_ID: 1000
        HOST_USER_NAME: nasrulirfan
        HOST_GROUP_NAME: nasrulirfan
      dockerfile: docker/php/Dockerfile
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./docker/logs/php.log:/var/log/fpm-php.www.log
    user: 1000:1000
    container_name: compasia-api
    expose:
      - "9000"
  mysql:
    container_name: mysql-db
    restart: always
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'compasia'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - ./docker/db-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    driver: bridge